In [ ]:
# Jorge Angon and Nick Garcia
#Food ingredients and allergens

In [49]:
#CSV upload and how to load
import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload() #Lets me choose a file

df=pd.read_csv('food_ingredients_and_allergens.csv') #reads the csv file into the pandas dataframe

df.head() #this displays the dataset

Saving food_ingredients_and_allergens.csv to food_ingredients_and_allergens (4).csv

,Food Product,Main Ingredient,Sweetener,Fat/Oil,Seasoning,Allergens,Prediction
0,Almond Cookies,Almonds,Sugar,Butter,Flour,"Almonds, Wheat, Dairy",Contains
1,Almond Cookies,Almonds,Sugar,Butter,Flour,"Almonds, Wheat, Dairy",Contains
2,Chicken Noodle Soup,Chicken broth,NaN,NaN,Salt,"Chicken, Wheat, Celery",Contains
3,Chicken Noodle Soup,Chicken broth,NaN,NaN,Salt,"Chicken, Wheat, Celery",Contains
4,Cheddar Cheese,Cheese,NaN,NaN,Salt,Dairy,Contains

In [50]:
#will save a copy of the original and find blanks, fill them and remove rows that are missing from prediction
df_original = df.copy()

df.isnull().sum() #Checks if there are missing values in each column

df1 = df.fillna('None') # fills missing value with a placeholder so the rows wont get lost
df = df1

df = df[df['Prediction'] != 'None'] #This removes rows if prediction is missing

df.shape

(398, 7)

In [51]:
#Turning the prediction text into numbers
from sklearn.preprocessing import LabelEncoder #Converts text to integers

le = LabelEncoder()

label = le.fit_transform(df['Prediction']) #Converts Prediction Column into a numeric labels

label #views the label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [52]:
#Replacing the text prediction column with numbered one

df.drop('Prediction', axis = 1, inplace = True)
df.drop('Allergens', axis = 1, inplace = True) #Drops allergens as well since it gives answer for prediction

df['Prediction'] = label #Adds prediction back as a numerical label instead

df.head()

/tmp/ipython-input-485342557.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Prediction', axis = 1, inplace = True)
/tmp/ipython-input-485342557.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('Allergens', axis = 1, inplace = True)
/tmp/ipython-input-485342557.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Prediction'] = label #Adds prediction back as a numerical label instead

          Food Product Main Ingredient Sweetener Fat/Oil Seasoning  Prediction
0       Almond Cookies         Almonds     Sugar  Butter     Flour           0
1       Almond Cookies         Almonds     Sugar  Butter     Flour           0
2  Chicken Noodle Soup   Chicken broth      None    None      Salt           0
3  Chicken Noodle Soup   Chicken broth      None    None      Salt           0
4       Cheddar Cheese          Cheese      None    None      Salt           0

In [53]:
#Turn ingredients into their own columns (hot encoding)

!pip -q install mlxtend
from mlxtend.preprocessing import TransactionEncoder

#Changes these into a list
data = df[['Food Product', 'Main Ingredient', 'Sweetener', 'Fat/Oil', 'Seasoning']].values.tolist()

#Fits and turns into true or false
a = TransactionEncoder()
a_data = a.fit(data).transform(data)

df_hot = pd.DataFrame(a_data, columns=a.columns_) #Changes to a data frame with column names
df_hot = df_hot.replace(False, 0) # Makes false = 0
df_hot = df_hot.replace(True, 1) # Makes true = 1

df_hot.head()

/tmp/ipython-input-2524634475.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_hot = df_hot.replace(True, 1) # Makes true = 1

,Almond Cookies,Almond milk,Almonds,Aloo Gobi,Aloo Paratha,Apple,Apple Cider,Apple Crisp,Apple Pie,Apples,...,Wheat flour,"Wheat flour, spices",Whipped cream,Yogurt,"Yogurt (milk, cultures)","Yogurt, Kashmiri red chili",Zucchini,Zucchini Bread,Zucchini Noodles,Zucchini Noodles with Pesto
0,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [54]:
#Combining the new ingredient columns with a prediction
df2 = df_hot.copy() #Adds numeric target column to the hot style encoding
df2['Prediction'] = df['Prediction']

df2.head()

,Almond Cookies,Almond milk,Almonds,Aloo Gobi,Aloo Paratha,Apple,Apple Cider,Apple Crisp,Apple Pie,Apples,...,"Wheat flour, spices",Whipped cream,Yogurt,"Yogurt (milk, cultures)","Yogurt, Kashmiri red chili",Zucchini,Zucchini Bread,Zucchini Noodles,Zucchini Noodles with Pesto,Prediction
0,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
1,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0

In [55]:
#Scaling

from sklearn import preprocessing

x = df2.drop('Prediction', axis = 1) #Change to x to make it easier to type. Also drops the target

df_scaled = preprocessing.scale(x) #scales x

df_scaled = pd.DataFrame(df_scaled, columns = x.columns) #Converts scaled array back to a data frame with same column names

df_scaled['Prediction'] = df2['Prediction'] #Adds the target back

df.head()

          Food Product Main Ingredient Sweetener Fat/Oil Seasoning  Prediction
0       Almond Cookies         Almonds     Sugar  Butter     Flour           0
1       Almond Cookies         Almonds     Sugar  Butter     Flour           0
2  Chicken Noodle Soup   Chicken broth      None    None      Salt           0
3  Chicken Noodle Soup   Chicken broth      None    None      Salt           0
4       Cheddar Cheese          Cheese      None    None      Salt           0

In [56]:
#Moving Food Product column to the end of the data set

OG_col = df.columns.values #orignal column
new_col = list(OG_col) #New column

new_col.remove('Food Product') #Removes food product

new_col.append('Food Product') #Adds food product at the end

df = df.reindex(columns = new_col) #Reorders the data frame columns

df.head()

  Main Ingredient Sweetener Fat/Oil Seasoning  Prediction         Food Product
0         Almonds     Sugar  Butter     Flour           0       Almond Cookies
1         Almonds     Sugar  Butter     Flour           0       Almond Cookies
2   Chicken broth      None    None      Salt           0  Chicken Noodle Soup
3   Chicken broth      None    None      Salt           0  Chicken Noodle Soup
4          Cheese      None    None      Salt           0       Cheddar Cheese